nzbget:
  build: nzbget
  ports:
    - "6789:6789"
  volumes:
    - ./config/nzbget:/volumes/config
    - ./media:/volumes/media

sonarr:
  build: sonarr
  links:
    - nzbget
  ports:
    - "8989:8989"
  volumes:
    - ./config/sonarr:/volumes/config/sonarr

couchpotato:
  build: couchpotato
  links:
    - nzbget
  ports:
    - "5050:5050"
  volumes:
    - ./config/couchpotato:/root/.couchpotato
